objects/MagicianType__mdt/MagicianType__mdt.object-meta.xml
<CustomObject>
    <label>MagicianType</label>
    <pluralLabel>MagicianTypes</pluralLabel>
</CustomObject>

objects/MagicianType__mdt/fields/AllowsSpells__c.field-meta.xml
<CustomField>
    <fullName>AllowsSpells__c</fullName>
    <defaultValue>false</defaultValue>
    <label>AllowsSpells</label>
    <type>Checkbox</type>
</CustomField>

objects/MagicianType__mdt/fields/BuildPoints__c.field-meta.xml
<CustomField>
    <fullName>BuildPoints__c</fullName>
    <label>BuildPoints</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/MagicianType__mdt/fields/ForcePoints__c.field-meta.xml
<CustomField>
    <fullName>ForcePoints__c</fullName>
    <label>ForcePoints</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/MagicianType__mdt/fields/List_Order__c.field-meta.xml
<CustomField>
    <fullName>List_Order__c</fullName>
    <label>List_Order</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/MagicianType__mdt/fields/RequiresSpellBonus__c.field-meta.xml
<CustomField>
    <fullName>RequiresSpellBonus__c</fullName>
    <defaultValue>false</defaultValue>
    <label>RequiresSpellBonus</label>
    <type>Checkbox</type>
</CustomField>

objects/MagicianType__mdt/fields/SpecialOptions__c.field-meta.xml
<CustomField>
    <fullName>SpecialOptions__c</fullName>
    <label>SpecialOptions</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/MagicianType__mdt/fields/TraditionOptions__c.field-meta.xml
<CustomField>
    <fullName>TraditionOptions__c</fullName>
    <label>TraditionOptions</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/MagicianType__mdt/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Adept</fullName>
                <default>true</default>
                <label>Adept</label>
            </value>
            <value>
                <fullName>Full</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/MetaraceAdjustment__mdt/MetaraceAdjustment__mdt.object-meta.xml
<CustomObject>
    <label>MetaraceAdjustment</label>
    <pluralLabel>MetaraceAdjustments</pluralLabel>
</CustomObject>

objects/MetaraceAdjustment__mdt/fields/Bonus__c.field-meta.xml
<CustomField>
    <fullName>Bonus__c</fullName>
    <defaultValue>false</defaultValue>
    <description>True if this adjustment is a bonus to modify the natural value, false if it should be considered part of the natural value</description>
    <label>Bonus</label>
    <type>Checkbox</type>
</CustomField>

objects/MetaraceAdjustment__mdt/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Attribute</fullName>
                <default>true</default>
                <label>Attribute</label>
            </value>
            <value>
                <fullName>Vision</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/MetaraceAdjustment__mdt/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Metarace</fullName>
                <default>true</default>
                <label>Metarace</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/MetaraceTemplate__mdt/MetaraceTemplate__mdt.object-meta.xml
<CustomObject>
    <label>MetaraceTemplate</label>
    <pluralLabel>MetaraceTemplates</pluralLabel>
</CustomObject>

objects/MetaraceTemplate__mdt/fields/Build_Point_Cost__c.field-meta.xml
<CustomField>
    <fullName>Build_Point_Cost__c</fullName>
    <label>Build Point Cost</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/SkillTemplate__mdt/SkillTemplate__mdt.object-meta.xml
<CustomObject>
    <label>SkillTemplate</label>
    <pluralLabel>SkillTemplates</pluralLabel>
</CustomObject>

objects/SkillTemplate__mdt/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Combat</fullName>
                <default>true</default>
                <label>Combat</label>
            </value>
            <value>
                <fullName>Physical</fullName>
            </value>
            <value>
                <fullName>Technical</fullName>
            </value>
            <value>
                <fullName>Magical</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Vehicle</fullName>
            </value>
            <value>
                <fullName>Ettiquette</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/SkillTemplate__mdt/fields/Concentrations__c.field-meta.xml
<CustomField>
    <fullName>Concentrations__c</fullName>
    <label>Concentrations</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/SkillTemplate__mdt/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>2048</length>
    <type>LongTextArea</type>
</CustomField>

objects/SkillTemplate__mdt/fields/Requires_Name__c.field-meta.xml
<CustomField>
    <fullName>Requires_Name__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Requires Name</label>
    <type>Checkbox</type>
</CustomField>

objects/SkillTemplate__mdt/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Build and Repair</fullName>
            </value>
            <value>
                <fullName>Knowledge</fullName>
            </value>
            <value>
                <fullName>Special</fullName>
            </value>
            <value>
                <fullName>Social</fullName>
            </value>
            <value>
                <fullName>Vehicle</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/SpellTemplate__mdt/SpellTemplate__mdt.object-meta.xml
<CustomObject>
    <label>SpellTemplate</label>
    <pluralLabel>SpellTemplates</pluralLabel>
</CustomObject>

objects/SpellTemplate__mdt/fields/DamageLevel__c.field-meta.xml
<CustomField>
    <fullName>DamageLevel__c</fullName>
    <label>Damage Level</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

objects/SpellTemplate__mdt/fields/Drain__c.field-meta.xml
<CustomField>
    <fullName>Drain__c</fullName>
    <label>Drain</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/SpellTemplate__mdt/fields/Duration__c.field-meta.xml
<CustomField>
    <fullName>Duration__c</fullName>
    <label>Duration</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/SpellTemplate__mdt/fields/ElementalEffect__c.field-meta.xml
<CustomField>
    <fullName>ElementalEffect__c</fullName>
    <label>Elemental Effect</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

objects/SpellTemplate__mdt/fields/MatterBased__c.field-meta.xml
<CustomField>
    <fullName>MatterBased__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Matter Based</label>
    <type>Checkbox</type>
</CustomField>

objects/SpellTemplate__mdt/fields/Range__c.field-meta.xml
<CustomField>
    <fullName>Range__c</fullName>
    <label>Range</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>LOS</fullName>
                <default>true</default>
                <label>LOS</label>
            </value>
            <value>
                <fullName>Limited</fullName>
            </value>
            <value>
                <fullName>Self</fullName>
            </value>
            <value>
                <fullName>Touch</fullName>
            </value>
            <value>
                <fullName>Extended</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/SpellTemplate__mdt/fields/RequiresName__c.field-meta.xml
<CustomField>
    <fullName>RequiresName__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Requires Name</label>
    <type>Checkbox</type>
</CustomField>

objects/SpellTemplate__mdt/fields/Subcategory__c.field-meta.xml
<CustomField>
    <fullName>Subcategory__c</fullName>
    <label>Subcategory</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

objects/SpellTemplate__mdt/fields/Target__c.field-meta.xml
<CustomField>
    <fullName>Target__c</fullName>
    <label>Target</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

objects/SpellTemplate__mdt/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Mana</fullName>
                <default>true</default>
                <label>Mana</label>
            </value>
            <value>
                <fullName>Physical</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/SpellTemplate__mdt/fields/Variants__c.field-meta.xml
<CustomField>
    <fullName>Variants__c</fullName>
    <label>Variants</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/Totem__mdt/Totem__mdt.object-meta.xml
<CustomObject>
    <label>Totem</label>
    <pluralLabel>Totems</pluralLabel>
</CustomObject>

objects/Totem__mdt/fields/Advantages__c.field-meta.xml
<CustomField>
    <fullName>Advantages__c</fullName>
    <label>Advantages</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/Totem__mdt/fields/Characteristics__c.field-meta.xml
<CustomField>
    <fullName>Characteristics__c</fullName>
    <label>Characteristics</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

objects/Totem__mdt/fields/Disadvantages__c.field-meta.xml
<CustomField>
    <fullName>Disadvantages__c</fullName>
    <label>Disadvantages</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

objects/Totem__mdt/fields/Favored_EnvIronment__c.field-meta.xml
<CustomField>
    <fullName>Favored_EnvIronment__c</fullName>
    <label>Favored EnvIronment</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/Totem__mdt/fields/Spell_Bonus__c.field-meta.xml
<CustomField>
    <fullName>Spell_Bonus__c</fullName>
    <label>Spell Bonus</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/TotemAdjustment__mdt/TotemAdjustment__mdt.object-meta.xml
<CustomObject>
    <label>Totem Adjustment</label>
    <pluralLabel>Totem Adjustments</pluralLabel>
</CustomObject>

objects/TotemAdjustment__mdt/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>EssenceLossMultiplier</fullName>
                <default>true</default>
                <label>EssenceLossMultiplier</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/TotemAdjustment__mdt/fields/Totem__c.field-meta.xml
<CustomField>
    <fullName>Totem__c</fullName>
    <label>Totem</label>
    <referenceTo>Totem__mdt</referenceTo>
    <relationshipLabel>Totem Adjustments</relationshipLabel>
    <relationshipName>Totem_Adjustments</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

objects/TotemAdjustment__mdt/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <label>Value</label>
    <precision>6</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

classes/DAOs/MetadataSelector.cls
public with sharing class MetadataSelector {

    public MetadataSelector() {
//getAll()
    }

    public static List<SampleHandle__mdt> getSampleHandles() {
        return [ SELECT Id, Label FROM SampleHandle__mdt ];
    }

    
    public static Map<Id, SkillTemplate__mdt> getSkillTemplates() {
        return new Map<Id, SkillTemplate__mdt>( [
        SELECT Id, Label,
        Category__c,
        Concentrations__c,
        Description__c,
        Requires_Name__c,
        Type__c        
        FROM SkillTemplate__mdt]);
    }



    public static Map<Id, MagicianType__mdt> getMagicianTypes() {
        return new Map<Id, MagicianType__mdt>( [
            SELECT Id, Label,
            AllowsSpells__c,
            BuildPoints__c,
            Description__c,
            ForcePoints__c,
            RequiresSpellBonus__c,
            SpecialOptions__c,
            TraditionOptions__c,
            List_Order__c,
            Type__c
            FROM MagicianType__mdt]);
    }

    public static Map<Id, MagicalTradition__mdt> getMagicialTraditions() {
        return new Map<Id, MagicalTradition__mdt>( [
            SELECT Id, Label,
            Description__c
            FROM MagicalTradition__mdt]);
    }

    public static Map<Id, Totem__mdt> getTotems() {
        return new Map<Id, Totem__mdt>( [
            SELECT Id, Label,
            Advantages__c,
            Characteristics__c,
            Disadvantages__c,
            Favored_EnvIronment__c,
            Spell_Bonus__c
            FROM Totem__mdt]);
    }

    public static Map<Id, List<TotemAdjustment__mdt>> getTotemAdjustments() {

        Map<Id, List<TotemAdjustment__mdt>> returnMap = new Map<Id, List<TotemAdjustment__mdt>>();

        for (TotemAdjustment__mdt adju : [
            SELECT Id, Label,
            Category__c,
            Description__c,
            Totem__c,
            Value__c
            FROM TotemAdjustment__mdt]) {

                if (!returnMap.containsKey(adju.Totem__c)) {
                    returnMap.put(adju.Totem__c, new List<TotemAdjustment__mdt>());
                }

                returnMap.get(adju.Totem__c).add(adju);

            }





           return returnMap;
    }

    public static Map<Id, SpellTemplate__mdt> getSpellTemplates() {
        return new Map<Id, SpellTemplate__mdt>( [
            SELECT Id, Label,
            Category__c,
            DamageLevel__c,
            Description__c,
            Drain__c,
            Duration__c,
            ElementalEffect__c,
            MatterBased__c,
            Options__c,
            Range__c,
            RequiresName__c,
            Source__c,
            Subcategory__c,
            Target__c,
            Type__c,
            Variants__c
            FROM SpellTemplate__mdt]);
    }



    // public static List<SkillTemplate__mdt> getSkillTemplates() {
    //     return [
    //     SELECT Id, Label,
    //     Category__c,
    //     Concentrations__c,
    //     Description__c,
    //     Requires_Name__c,
    //     Type__c        
    //     FROM SkillTemplate__mdt];
    // }


    public static Map<Id, MetaraceTemplate__mdt> getMetaraceTemplates() {
        return new Map<Id, MetaraceTemplate__mdt>([
            SELECT Id, Label,
            Build_Point_Cost__c,
            Commentary__c,
            Habitat__c,
            Habits__c,
            Identification__c,
            Image__c,
            Notes__c,
            RunningMultiplier__c,
            Taxonomy__c,
            Young__c
            FROM MetaraceTemplate__mdt
        ]);


        //return new Map<Id, MetaraceTemplate__mdt>(MetaraceTemplate__mdt.getAll().values());
    }

    // metarace templatye Id -> list of adjustments
    public static Map<Id, List<MetaraceAdjustment__mdt>> getMetaraceAdjustments() {
        Map<Id, List<MetaraceAdjustment__mdt>> returnMap = new Map<Id, List<MetaraceAdjustment__mdt>>();


        // SOQL to get ordering

        for (MetaraceAdjustment__mdt mdt : [ SELECT Id, Label,
        Bonus__c,
        Category__c,
        Description__c,
        Field__c,
        MetaraceTemplate__c,
        Type__c,
        Value__c
        FROM MetaraceAdjustment__mdt ORDER BY Category__c, Bonus__c, Description__c

        ]) {
            if (!returnMap.containsKey(mdt.MetaraceTemplate__c)) {
                returnMap.put(mdt.MetaraceTemplate__c, new List<MetaraceAdjustment__mdt>());
            }

            returnMap.get(mdt.MetaraceTemplate__c).add(mdt);
        }

        return returnMap;
    }


    public static MetadataSelectorResponse getAllTemplates() {
        MetadataSelectorResponse response = new MetadataSelectorResponse();

        response.MetaraceTemplateMap = getMetaraceTemplates();
        response.MetaraceAdjustmentMap = getMetaraceAdjustments();
        response.skillTemplateMap = getSkillTemplates();
        response.magicianTypeMap = getMagicianTypes();
        response.totemMap = getTotems();
        response.spellTemplateMap = getSpellTemplates();
        response.totemAdjustmentMap = getTotemAdjustments();
        return response;
    }

    public class MetadataSelectorResponse {
        @AuraEnabled
        public Map<Id, MetaraceTemplate__mdt> metaraceTemplateMap;

        @AuraEnabled
        public Map<Id, List<MetaraceAdjustment__mdt>> metaraceAdjustmentMap;

        @AuraEnabled
        public Map<Id, SkillTemplate__mdt> skillTemplateMap;

        @AuraEnabled
        public Map<Id, MagicianType__mdt> magicianTypeMap;

        @AuraEnabled
        public Map<Id, Totem__mdt> totemMap;

        @AuraEnabled
        public Map<Id, List<TotemAdjustment__mdt>> totemAdjustmentMap;

        @AuraEnabled
        public Map<Id, SpellTemplate__mdt> spellTemplateMap;



        // Totem__mdt

        // @AuraEnabled
        // public List<SkillTemplate__mdt> skillTemplateList;

    }
}