objects/SkillAssign__c/SkillAssign__c.object-meta.xml
<CustomObject>
    <label>SkillAssign</label>
    <nameField>
        <label>SkillAssign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SkillAssigns</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/SkillAssign__c/fields/Rating__c.field-meta.xml
<CustomField>
    <fullName>Rating__c</fullName>
    <label>Rating</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/SkillAssign__c/fields/SkillTemplateId__c.field-meta.xml
<CustomField>
    <fullName>SkillTemplateId__c</fullName>
    <label>SkillTemplateId</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

objects/SkillAssign__c/fields/Special_Skill_Name__c.field-meta.xml
<CustomField>
    <fullName>Special_Skill_Name__c</fullName>
    <label>Special Skill Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/SkillAssign__c/fields/SRcharacter__c.field-meta.xml
<CustomField>
    <fullName>SRcharacter__c</fullName>
    <label>SRcharacter</label>
    <referenceTo>SRcharacter__c</referenceTo>
    <relationshipLabel>SkillAssigns</relationshipLabel>
    <relationshipName>SkillAssigns</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

objects/SpellAssign__c/SpellAssign__c.object-meta.xml
<CustomObject>
    <label>Spell Assign</label>
    <nameField>
        <label>SpellAssign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Spell Assigns</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/SpellAssign__c/fields/Drain__c.field-meta.xml
<CustomField>
    <fullName>Drain__c</fullName>
    <label>Drain</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

objects/SpellAssign__c/fields/Duration__c.field-meta.xml
<CustomField>
    <fullName>Duration__c</fullName>
    <label>Duration</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

objects/SpellAssign__c/fields/SpellTemplateId__c.field-meta.xml
<CustomField>
    <fullName>SpellTemplateId__c</fullName>
    <label>Spell Template Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

objects/SpellAssign__c/fields/SRcharacter__c.field-meta.xml
<CustomField>
    <fullName>SRcharacter__c</fullName>
    <label>SRcharacter</label>
    <referenceTo>SRcharacter__c</referenceTo>
    <relationshipLabel>Spell Assigns</relationshipLabel>
    <relationshipName>Spell_Assigns</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

objects/SRcharacter__c/SRcharacter__c.object-meta.xml
<CustomObject>
    <label>SRcharacter</label>
    <nameField>
        <label>Handle</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SRcharacters</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/SRcharacter__c/fields/Body__c.field-meta.xml
<CustomField>
    <fullName>Body__c</fullName>
    <label>Body</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/SRcharacter__c/fields/Charisma__c.field-meta.xml
<CustomField>
    <fullName>Charisma__c</fullName>
    <label>Charisma</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/SRcharacter__c/fields/Intelligence__c.field-meta.xml
<CustomField>
    <fullName>Intelligence__c</fullName>
    <label>Intelligence</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/SRcharacter__c/fields/MagicalTradition__c.field-meta.xml
<CustomField>
    <fullName>MagicalTradition__c</fullName>
    <label>MagicalTradition</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Shamanic</fullName>
            </value>
            <value>
                <fullName>Hermetic</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

objects/SRcharacter__c/fields/MagicianTypeId__c.field-meta.xml
<CustomField>
    <fullName>MagicianTypeId__c</fullName>
    <label>MagicianTypeId</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

objects/SRcharacter__c/fields/MetaraceTemplate__c.field-meta.xml
<CustomField>
    <fullName>MetaraceTemplate__c</fullName>
    <label>MetaraceTemplate</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

objects/SRcharacter__c/fields/Quickness__c.field-meta.xml
<CustomField>
    <fullName>Quickness__c</fullName>
    <label>Quickness</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/SRcharacter__c/fields/Real_Name__c.field-meta.xml
<CustomField>
    <fullName>Real_Name__c</fullName>
    <label>Real Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/SRcharacter__c/fields/Short_Notes__c.field-meta.xml
<CustomField>
    <fullName>Short_Notes__c</fullName>
    <label>Short Notes</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

objects/SRcharacter__c/fields/Strength__c.field-meta.xml
<CustomField>
    <fullName>Strength__c</fullName>
    <label>Strength</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

objects/SRcharacter__c/fields/TotemId__c.field-meta.xml
<CustomField>
    <fullName>TotemId__c</fullName>
    <label>TotemId</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

objects/SRcharacter__c/fields/Willpower__c.field-meta.xml
<CustomField>
    <fullName>Willpower__c</fullName>
    <label>Willpower</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

classes/DAOs/SRcharacterDao.cls
public with sharing class SRcharacterDao extends fflib_SObjectSelector {
 
    public Schema.SObjectType getSObjectType(){
       return SRcharacter__c.sObjectType;
    }
  
    public List<Schema.SObjectField> getSObjectFieldList(){
       return new List<Schema.SObjectField> {
          SRcharacter__c.Id,
          SRcharacter__c.Name,
          SRcharacter__c.Short_Notes__c
       };
    }


    public SRcharacterDao() {

    }

    public List<SRcharacter__c> getCharacters() {
        return [ SELECT Id,
        Name,
        Real_Name__c FROM SRcharacter__c ];
    }

    public List<SRcharacter__c> getCharacterNames() {
        fflib_QueryFactory qFactory = newQueryFactory();

        return (List<SRcharacter__c>) Database.query( qFactory.toSOQL() );


        // return [ SELECT Id, Name FROM SRcharacter__c ];
    }

    public SRcharacter__c getCharById(Id charId) {
        fflib_QueryFactory qFactory = newQueryFactory();
        qFactory.selectFields(new List<String>{
            'Real_Name__c',
            'Body__c',
            'Strength__c',
            'Quickness__c',
            'Willpower__c',
            'Intelligence__c',
            'Charisma__c',
            'MetaraceTemplate__c',
            'TotemId__c',
            'ElementalOption__c',
            'MagicalTradition__c',
            'MagicianTypeId__c'
        })
        .setCondition('Id = :charId');

        qFactory.subSelectQuery('SkillAssigns__r')
        .selectFields(new List<String>{
            'Name',
            'Rating__c',
            'SkillTemplateId__c',
            'Special_Skill_Name__c'
        });

        qFactory.subSelectQuery('Spell_Assigns__r')
        .selectFields(new List<String>{
            'Name',
            'Drain__c',
            'Duration__c',
            'Exclusive__c',
            'Fetish__c',
            'Rating__c',
            'SpecialName__c',
            'SpellTemplateId__c',
            'SpellTemplateVariantIndex__c'
        });

        return (SRcharacter__c) Database.query( qFactory.toSOQL() );

    }

    public Boolean saveChar(SR_AppWrapperCtrl.CharacterDataWrapper charWrapper) {
        fflib_ISObjectUnitOfWork uow = new fflib_SObjectUnitOfWork(
            new List<Schema.SObjectType>{
                SRcharacter__c.sObjectType,
                SkillAssign__c.sObjectType
            }
        );

        uow.registerUpsert(charWrapper.character);
        uow.registerUpsert(charWrapper.skillAssigns);

        for (SkillAssign__c skill : charWrapper.skillAssigns) {
            uow.registerRelationship(skill, SkillAssign__c.SRcharacter__c, charWrapper.character);
        }
        uow.registerDeleted(charWrapper.skillAssignsToDelete);


        try {
            uow.commitWork();
        } catch (Exception ex) {
            return false;
        }

        return true;        
        //return Database.upsert(charToSave, false);
    }
}